[tool.poetry]
name = "PyABAC"
version = "0.0.3"
description = "A simple ABAC library for Python."
authors = ["Julian DeMille <julian.demille@demilletech.net>"]
readme = "README.rst"
license = "LGPL-3.0+"
packages = [
    { include = "abac", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = { version = "^3.4", optional = true }
# umongo = { version = "^0.15.0", optional = true }
gremlinpython = { version = "^3.3", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "^18.3-alpha.0"
flake8 = "^3.5"
flake8-bugbear = "^18.8"
sphinx = "^1.8"
sphinx-rtd-theme = "^0.4.1"
mypy = "^0.630.0"
sphinx_autodoc_typehints = "^1.3"

[tool.poetry.extras]
aiohttp = ["aiohttp"]
umongo = ["umongo"]
gremlin = ["gremlinpython"]
