[tool.poetry]
name = "aiosplinter"
version = "0.1.2"
description = "Asynchronous splinter wrapper Python library"
authors = ["Roman Inflianskas <infroma@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["splinter", "web", "browser", "web-browser", "automation", "selenium", "async", "asyncio"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
repository = "https://github.com/rominf/aiosplinter"

[tool.poetry.dependencies]
python = "^3.6"
poetry-version = "^0.1.2"
splinter = "^0.9.0"
aioify = {git = "https://github.com/yifeikong/aioify.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
